name: cicd

on:
  workflow_dispatch:  
  
jobs:
 code:
   runs-on: ubuntu-latest
   steps:
     - name: clone the code
       run: echo "cloning the code"
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Build using Docker
       run: echo "Building using dockcer"
 test:
   runs-on: ubuntu-latest
   steps:
     - name: Running test cases
       run: echo " testing the app"
       
 deploying:
   runs-on: ubuntu-latest
   steps:
     - name: deploying on the machine
       run: echo "deploying the code"
     
    
    
